version: '3.7'

networks:
  lan_docker:

services:

  server:
    hostname: server
    build:
      context: ./server
    restart: always
    ports:
      - 8888:8888
    networks:
      - lan_docker

  client:
    hostname: client
    build:
      context: ./client
    restart: always
    ports:
      - 8081:8081
    networks:
      - lan_docker
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8888